language: java
jdk:
  - openjdk11
  - openjdk10
  - openjdk9
script:
  - make testSel
  - make testRnd
  - make testRnd maxl=21
  - make testRnd maxl=20
  - make testRnd probe=100
  - make testRnd probe=200
  - make testRnd probe=500
  - make testRnd probe=1000